namespace PokemonDataExplorer.Api;

public class PokemonReport : IDocument
{
    private readonly PokemonSmallDataDto _pokemonSmallDataDto;

    public PokemonReport(PokemonSmallDataDto pokemonSmallDataDto)
    {
        _pokemonSmallDataDto = pokemonSmallDataDto;
    }

    public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

    public void Compose(IDocumentContainer container)
    {
        container.Page(page =>
        {
            page.Margin(50);

            page
                .Header()
                .Text("Pokemon Report")
                .FontSize(24)
                .Bold()
                .AlignCenter();

            page
                .Content()
                .PaddingTop(20)
                .Column(column =>
                {
                    column.Item().Text($"ID: {_pokemonSmallDataDto.Id}").FontSize(16).Bold();
                    column.Item().Text($"Name: {_pokemonSmallDataDto.Name.ToUpper()}").FontSize(16).Bold();
                    column.Item().PaddingBottom(20).Text("Picture:").FontSize(16).Bold();

                    if (_pokemonSmallDataDto.PokemonPicture is not null)
                        column
                            .Item()
                            .Border(2)
                            .BorderColor(Colors.Black)
                            .Padding(5)
                            .Image(_pokemonSmallDataDto.PokemonPicture);
                    else
                        column
                            .Item()
                            .Border(2)
                            .BorderColor(Colors.Black)
                            .Padding(5)
                            .Text("No image available")
                            .Italic();
                });

            page
                .Footer()
                .AlignCenter()
                .Text($"Generated by Pokemon Data Explorer API - Generated at: {DateTime.Now.ToString()}");
        });
    }
}
